name: exe3

on:
  push:
    paths:
      - 'exe6/main.c'
jobs:
  exe3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: insper-embarcados/pico-build@v1
      - uses: insper-embarcados/actions-wokwi-test@v3
        if: ${{ always() }}
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          test_name: exe6
      - uses: insper-embarcados/actions-firmware-rubric-check@v0
        if: ${{ always() }}
        with:
          c_file: exe6/main.c
          rubric_file: exe6/rubric_firmware.yml
      - uses: insper-embarcados/actions-embedded-check@v1
        if: ${{ always() }}
        with:
          c_file: exe6/main.c
      - uses: insper-embarcados/actions-cppcheck@v1
        if: ${{ always() }}
        with:
          c_file: exe6/main.c
